spring.application.name=simakerja-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
cors.origin.urls=${CORS_ORIGINS}

# App
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
app.cookie.secure=${COOKIE_SECURE:false}

# Datasource - Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.properties.hibernate.format_sql=${JPA_SHOW_SQL}
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# Google Login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET_KEY}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Minio
minio.url=${MINIO_ENDPOINT:http://localhost:9000}
minio.access.key=${MINIO_ACCESS_KEY_ID}
minio.access.secret=${MINIO_SECRET_ACCESS_KEY}
minio.ssl=${MINIO_SSL:false}
minio.bucket.name=partner-assets
minio.presigned.expiry=60

# Cleanup File
cleanup.file.threshold-hours=24
cleanup.file.enabled=true

# JWT
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION_MS:600000}

jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION_MS:604800000}

# Auth
app.max.failed.attempts=${MAX_FAILED_ATTEMPTS:5}
app.lockout.duration.minutes=${LOCKOUT_DURATION_MINUTES:15}

# Monitoring
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.mail.enabled=false

# OCR Configuration
ocr.tessdata.path=${TESSDATA_PATH:tessdata}
ocr.dpi=${OCR_DPI:300}

resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL:hello@simakerja.com}